name: stock_saathi
description: Har Dukaan Ka Digital Saathi
publish_to: 'none'

version: 0.1.0+1

environment:
sdk: ">=3.12.0 <4.0.0"

dependencies:
flutter:
sdk: flutter

sqflite: ^2.4.1
path: ^1.9.1
flutter_riverpod: ^2.6.1
intl: ^0.20.2

flutter:
uses-material-design: true

